[package]
name = "event-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zmq = "0.9"
uuid = { version = "0.8", features = ["v4"] }
rand = "0.8.5"
thiserror = "1.0"