version: "3.0"

networks:
  zmqevents:
    driver: bridge

services:
  engine:
    container_name: engine
    image: tapis/event-engine-ex-app
    networks:
      - zmqevents

  pyplugin:
    container_name: pyplugin
    image: tapis/events-engine-ex-pyplugin
    networks:
      - zmqevents
